dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: bSc5k0JAYnb3ONzO1HRQp7CSDD/l6vN31MZrJo2AYIn+s70UayCpKFH5f32HmffvyWf9Nmxe6aF1Q6JKkyR0mpcRpKvx7RznaAJkk82X40vpu517Col/fOU4RIYhLNPQk5G8QxEAAXRYkRtglbJ/GjNABCx3y1fu613Jafz91aI4ds6XVn0bq1Z2nNRww+I79UUruqq/m0xONa6E+NPhU/wgw/CpyY6VYRaOMYWCTpipPt10j8vxCpYNztQrRMR9vCB9FbqSo7x+MasBp1yKPbQ+al3/8T4jj89pSyo17fEyRigMruVUSeLuv2CPi7GdM/UFv2f4Fko7ZBK7SP99sHWjuwc1K6+8A1+M772Zt/rxM7oOnz7TzPBZpZh3p011VaKd5+Ccu+T4iTnlB3BlOuQqWfwwRHwjkzce4Ny/HTXbEm0JIK77v2VBJHKY0YkZQWDkDoMnyScSwTvIngJvt5mIXDrJMpMJQ++kJdkjcKxbzlSFG0cQXfIpN86cCHo06CLpL+Hy1zATqHFPhgPC/HrrKC5v/sOXXN9nmtr1hAjlZEEVQbIwivgWhCl4rbxLJ/U/YTrxP0xBJ0f9fo5DH7eA12t717w/mCKE6nRS+ZDM+T6bMW84UuljiKmVKay3//AzJmR1Nmbbm+OwohCZOTRTF6aP0yC8tXEJzGzRlag=
  file: Gerbers/MNT-101_gerbers.zip
  on:
    repo: w4xzr/MNT-101
  skip_cleanup: 'true'
